print(" it will be imported as matplotlib.pyplot  ")
print(" There are various  graphs which are Enlisted below")
print(" 1. Line Chart")
print(" 2. Scatter Plot")
print(" 3. Bar Graph")
print(" 4. Histogram")
print(" 5. Pie-Chart")
print(" 6. Box plot")
print(" 7. Area plot")
print(" 8. Heat Maps")
print(" 9. Bubble chart")
print(" 10.Stack Plot")